create table salesdata(
Id int ,
Value int,
Running_total int)


insert into salesdata(id,value)
values (1,10),(2,20),(3,40),(4,45)

DROP TABLE SALESDATA


select * from salesdata

DECLARE @ID INT;
DECLARE @VALUE INT;
DECLARE @RUNNING_TOTAL INT = 0;


DECLARE RUNNING_TOTAL_CURSOR CURSOR FOR
SELECT ID, VALUE FROM SALESDATA ORDER BY ID;


OPEN RUNNING_TOTAL_CURSOR;

FETCH NEXT FROM RUNNING_TOTAL_CURSOR INTO @ID, @VALUE;


WHILE @@FETCH_STATUS = 0
BEGIN
    SET @RUNNING_TOTAL = @RUNNING_TOTAL + @VALUE;

    UPDATE SALESDATA
    SET RUNNING_TOTAL = @RUNNING_TOTAL
    WHERE ID = @ID;

    FETCH NEXT FROM RUNNING_TOTAL_CURSOR INTO @ID, @VALUE;
END;


CLOSE RUNNING_TOTAL_CURSOR;
DEALLOCATE RUNNING_TOTAL_CURSOR;
