CREATE TABLE EMPLOYEE(
EMPLOYEEID INT PRIMARY KEY ,
FIRSTNAME VARCHAR(100),
LASTNAME VARCHAR(100) UNIQUE,
DATEOFBIRTH DATE,
GENDER CHAR(2),
DEPARTMENTID INT)

INSERT INTO EMPLOYEE_TESTINDEX
VALUES
(101,'VEERAMANI','VEZHAVENTHAN','1998-09-09','M',1001),
(102,'DEVI','RAMRAJ','2007-08-14','F',1002),
(103,'VIJAY','RAJA','1990-06-18','M',1003)



SELECT * INTO EMPLOYEE_TESTINDEX FROM EMPLOYEE


CREATE INDEX IDX_FIRSTNAME
ON EMPLOYEE_TESTINDEX(FIRSTNAME,LASTNAME)

SELECT* FROM EMPLOYEE_TESTINDEX  WHERE  LASTNAME='RAMRAJ' AND FIRSTNAME='DEVI' 